"""Generate a runnable OMNeT++ ``[Config]`` from a ZeroConfigTSN-style spec.

Strategy (correct-by-construction): rather than synthesise a full TSN config
from nothing — which means re-deriving stream identification, PCP encoding,
classifier indices, clock wiring, etc. — we **extend an existing, working base
configuration** and emit only the deltas the user chose: TSN feature toggles
and per-traffic-class shaper settings. The output is written as a *separate*
ini that ``include``s the original showcase ini, so the showcase is never
modified.

Feature → INI mappings and the compatibility rules below are taken from the
INET TSN showcases (verified patterns).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

# feature key -> (label, ini key pattern). The pattern gets " = true/false".
FEATURES: list[tuple[str, str, str]] = [
    ("hasEgressTrafficShaping", "Egress traffic shaping (TAS/CBS)", "*.*Switch.hasEgressTrafficShaping"),
    ("hasIngressTrafficFiltering", "Ingress filtering / policing (PSFP)", "*.*Switch.hasIngressTrafficFiltering"),
    ("hasFramePreemption", "Frame preemption (802.1Qbu)", "*.*Switch.hasFramePreemption"),
    ("hasTimeSynchronization", "Time synchronization (gPTP)", "*.*.hasTimeSynchronization"),
    ("hasStreamRedundancy", "Stream redundancy / FRER (802.1CB)", "*.*.hasStreamRedundancy"),
    ("hasCutthroughSwitching", "Cut-through switching", "*.*Switch.hasCutthroughSwitching"),
]
FEATURE_LABELS = {k: label for k, label, _ in FEATURES}
FEATURE_PATTERNS = {k: pat for k, _, pat in FEATURES}

SCHEDULING_CHOICES = ["inherit", "CBS", "TAS", "off"]
TRISTATE = ["inherit", "on", "off"]

_QUEUE = "*.*Switch.eth[*].macLayer.queue"


@dataclass
class TrafficClass:
    name: str
    index: int                 # traffic class / gate index (per IEEE 802.1Q table)
    scheduling: str = "inherit"  # inherit | CBS | TAS | off
    idle_slope: str = "40Mbps"  # CBS reserved bandwidth
    tas_open_us: float = 100.0  # TAS gate open duration (microseconds)
    tas_cycle_us: float = 1000.0  # TAS gate cycle duration (microseconds)


@dataclass
class ConfigSpec:
    name: str = "TsnTool_Custom"
    base: str = ""
    description: str = "Generated by TSN Tool"
    features: dict[str, str] = field(default_factory=dict)   # key -> inherit|on|off
    classes: list[TrafficClass] = field(default_factory=list)


# --- compatibility checks --------------------------------------------------
def compatibility_warnings(spec: ConfigSpec) -> list[str]:
    """Return human-readable warnings about the chosen combination."""
    w: list[str] = []
    feat = spec.features
    shaping_on = feat.get("hasEgressTrafficShaping") == "on"
    shaping_off = feat.get("hasEgressTrafficShaping") == "off"
    filtering_on = feat.get("hasIngressTrafficFiltering") == "on"

    uses_shaper = any(c.scheduling in ("CBS", "TAS") for c in spec.classes)
    if uses_shaper and shaping_off:
        w.append("Per-class CBS/TAS is set but egress traffic shaping is turned OFF — "
                 "enable 'Egress traffic shaping' or the shaper settings are ignored.")
    if uses_shaper and not shaping_on and spec.base in ("StandardEthernet", ""):
        w.append("Per-class shaping needs a TSN base with PCP stream encoding — "
                 "extend 'ManualTsn' or 'AutomaticTsn', not 'StandardEthernet'.")

    if feat.get("hasFramePreemption") == "on":
        w.append("Frame preemption replaces the monolithic egress queue with express/"
                 "preemptable sub-MACs; combining it with per-class TAS gating may need "
                 "manual sub-MAC configuration (see combiningfeatures/fpandtas).")
        if any(c.scheduling == "TAS" for c in spec.classes):
            w.append("TAS gating + frame preemption selected together — verify gate "
                     "durations against the preemptable MAC after running.")

    if feat.get("hasTimeSynchronization") == "off" and any(c.scheduling == "TAS" for c in spec.classes):
        w.append("TAS gates are clock-driven; turning OFF time synchronization can desync "
                 "gate schedules across switches.")

    # CBS idleSlope sanity (very rough: warn on obviously large reservations)
    for c in spec.classes:
        if c.scheduling == "CBS" and c.idle_slope.lower().endswith("gbps"):
            try:
                if float(c.idle_slope[:-4]) > 1:
                    w.append(f"Class '{c.name}' idleSlope {c.idle_slope} exceeds a 1 Gbps link.")
            except ValueError:
                pass
    if not spec.base:
        w.append("No base configuration selected — pick one to extend.")
    return w


# --- generation ------------------------------------------------------------
def _feature_lines(spec: ConfigSpec) -> list[str]:
    lines: list[str] = []
    for key, _label, pattern in FEATURES:
        state = spec.features.get(key, "inherit")
        if state == "inherit":
            continue
        lines.append(f"{pattern} = {'true' if state == 'on' else 'false'}")
        if key == "hasFramePreemption" and state == "on":
            lines.append('*.*Switch.eth[*].macLayer.typename = "EthernetPreemptingMacLayer"')
            lines.append('*.*Switch.eth[*].phyLayer.typename = "EthernetPreemptingPhyLayer"')
    return lines


def _class_lines(spec: ConfigSpec) -> list[str]:
    lines: list[str] = []
    for c in spec.classes:
        if c.scheduling == "inherit":
            continue
        tsa = f"{_QUEUE}.transmissionSelectionAlgorithm[{c.index}]"
        gate = f"{_QUEUE}.transmissionGate[{c.index}]"
        lines.append(f"# class '{c.name}' (index {c.index}): {c.scheduling}")
        if c.scheduling == "CBS":
            lines.append(f'{tsa}.typename = "Ieee8021qCreditBasedShaper"')
            lines.append(f"{tsa}.idleSlope = {c.idle_slope}")
        elif c.scheduling == "TAS":
            closed = max(0.0, c.tas_cycle_us - c.tas_open_us)
            lines.append(f'{tsa}.typename = ""')  # gating instead of credit-based
            lines.append(f"{gate}.initiallyOpen = true")
            lines.append(f"{gate}.durations = [{c.tas_open_us:g}us, {closed:g}us]")
        elif c.scheduling == "off":
            lines.append(f'{tsa}.typename = ""')
    return lines


def generate_config_text(spec: ConfigSpec) -> str:
    out = [f"[Config {spec.name}]"]
    if spec.base:
        out.append(f"extends = {spec.base}")
    out.append(f'description = "{spec.description}"')

    feats = _feature_lines(spec)
    if feats:
        out.append("")
        out.append("# --- TSN features ---")
        out.extend(feats)

    cls = _class_lines(spec)
    if cls:
        out.append("")
        out.append("# --- per-traffic-class shaping ---")
        out.extend(cls)

    return "\n".join(out) + "\n"


def generate_ini_text(spec: ConfigSpec, base_ini_name: str) -> str:
    """Full generated ini content: include the showcase ini, then the config."""
    header = (
        "# Generated by TSN Tool — safe to delete/regenerate.\n"
        f"# Extends '{spec.base}' from {base_ini_name}; the original is not modified.\n\n"
        f"include {base_ini_name}\n\n"
    )
    return header + generate_config_text(spec)


def write_generated_ini(spec: ConfigSpec, base_ini_path: str | Path,
                        out_name: str = "tsntool_generated.ini") -> Path:
    base_ini_path = Path(base_ini_path)
    out_path = base_ini_path.parent / out_name
    out_path.write_text(generate_ini_text(spec, base_ini_path.name), encoding="utf-8")
    return out_path
